### **Import and Cleaning**

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('properties - properties.csv')
df.head()

,property_id,assd_improvement_value,assd_land_value,assd_total_value,assd_year,assessor_value_to_most_recent_sale_ratio,basement_finish,basement_square_feet,basement_type_code,block,...,commercialOverlay2,specialPurposeDistrict,splitZone,historicDistrict,landmark,zoningMap,sanbornMap,isCondoFlag,subwayEntrancesAndDistances,ownership
0,53ba347d-5c3f-470c-ba34-7d5c3f770c24,NaN,NaN,1170.0,2018,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":2,""has_green_emails"":tr..."
1,0a50c528-b992-5ad9-aa5f-81b5c1ebeed0,17560.0,4400.0,21960.0,2018,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":3,""has_green_emails"":tr..."
2,435161a6-47ea-5158-ae4a-1fdaf925a9c3,0.0,3900.0,3900.0,2019,0.231056,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":2,""has_green_emails"":tr..."
3,eb03203d-a094-5c26-956f-ab6695a0c2a3,0.0,90.0,90.0,2018,0.000414,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":0,""has_green_emails"":fa..."
4,30f28da3-655b-5edc-bdb4-a87b0ec3fbba,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":3,""has_green_emails"":tr..."

In [2]:
#list column names to determine importance
for col in df.columns: 
    print(col)

property_id
assd_improvement_value
assd_land_value
assd_total_value
assd_year
assessor_value_to_most_recent_sale_ratio
basement_finish
basement_square_feet
basement_type_code
block
building_area
construction_type
district
effective_year_built
electric_energy
exterior_walls
fips
fireplace_ind
fireplace_number
fireplace_type
floor
fips_county
fips_state
floors
foreclosure
formatted_apn
foundation
frame
fuel
garage
heating
in_state_roe
legal_description
location
lot_size_acres
lot_size_depth_feet
lot_size_frontage_feet
lot_size_sqft
mailing_std_carrier_code
mailing_std_city
mailing_std_direction_left
mailing_std_direction_right
mailing_std_house_nbr
mailing_std_house_nbr2
mailing_std_house_nbr_suffix
mailing_std_mode
mailing_std_state
mailing_std_street
mailing_std_unit_nbr
mailing_std_unit_type
mailing_std_zip4
mailing_std_zip5
market_total_value
market_value_improvement
market_value_land
mortgages
most_recent_mtg
most_recent_sale
municipality
owner_names
owner_occupied
owner_std1_first_name
owner_std1_last_name
owner_std1_middle_name
owner_std1_ownership_rights
owner_std1_suffix
owner_std_name1_full
owner_std1_entity_type
owner_std2_first_name
owner_std2_last_name
owner_std2_middle_name
owner_std_name2_full
owner_std2_entity_type
parcel_shape_ids
pool
pool_code
property_class_id
quality
reonomy_sources
roof_cover
roof_type
sales
section
sewer
situs_std_carrier_code
situs_std_city
situs_std_direction_left
situs_std_direction_right
situs_std_house_nbr
situs_std_mode
situs_std_state
situs_std_street
situs_std_unit_nbr
situs_std_unit_type
situs_std_zip4
situs_std_zip5
std_land_use_code
std_land_use_code_category
std_land_use_code_description
sum_building_sqft
sum_buildings_nbr
sum_commercial_units
sum_number_of_bedrooms
sum_number_of_full_baths
sum_number_of_half_baths
sum_number_of_quarter_baths
sum_number_of_rooms
sum_number_of_three_quarter_baths
sum_residential_units
tax_amount
tax_year
total_baths
total_units
utilities
water
year_built
zoning
neighborhood_shape_list
opp_zone
msa_name
neighborhood_name
mcd_name
building_update_time
master_update_time
mtg_update_time
owner_update_time
sale_update_time
shape_update_time
assemblage_id
tax_update_time
all_field_update_time
occupants
active
deprecation_date
assd_to_market_ratio
assd_change
assd_change_pct
tax_rate
tax_change
tax_change_pct
tax_amount_is_interpolated
tax_data
transitional_assessed_value
transitional_exemption_value
billable_assessed_value
exemptions_and_abatements
gross_tax_amount
gross_tax_rate
bins
owningEntity
registrationState
entityAddress
regulatedUnits
aUnits
bUnits
registrationStatus
registrationDate
registrationExpiration
status1
status2
status3
outstandingLitigation
closedLitigation
history
financials
boroughId
lot
parentId
address
crossStreets
buildingName
buildingFrontage
buildingDepth
largestFloorPlate
usf
builtFAR
buildingClass
buildingClassDescription
buildingClassCategory
buildingPropertyTypes
officeArea
garageArea
storageArea
factoryArea
retailArea
otherArea
residentialArea
commercialArea
rentableArea
zoningDistrict1
zoningDistrict2
commercialOverlay1
commercialOverlay2
specialPurposeDistrict
splitZone
historicDistrict
landmark
zoningMap
sanbornMap
isCondoFlag
subwayEntrancesAndDistances
ownership

In [3]:
#sort by state to make external site usage easier 
#df.sort_values(by=['fips_state'])
#df = df.reset_index(drop=True)
#reorder state as first column
col = df.pop('fips_state')
df.insert(0, col.name, col)
df = df.sort_values(by=['fips_state']).reset_index(drop=True)
df.head()

,fips_state,property_id,assd_improvement_value,assd_land_value,assd_total_value,assd_year,assessor_value_to_most_recent_sale_ratio,basement_finish,basement_square_feet,basement_type_code,...,commercialOverlay2,specialPurposeDistrict,splitZone,historicDistrict,landmark,zoningMap,sanbornMap,isCondoFlag,subwayEntrancesAndDistances,ownership
0,AK,b22519ce-6df8-5d5e-a102-6e18c529c66f,0.0,32400.0,32400.0,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":0,""has_green_emails"":fa..."
1,AK,8b892404-edde-4355-8924-04edde13553a,238200.0,34000.0,272200.0,2019,0.899271,NaN,NaN,BFL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":1,""has_green_emails"":fa..."
2,AL,7900d820-292a-5311-96bc-a379772f14d3,NaN,NaN,3000.0,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":2,""has_green_emails"":tr..."
3,AL,30aa3df9-e703-5b93-958e-88ee3118d284,0.0,5400.0,5400.0,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":1,""has_green_emails"":tr..."
4,AL,e02ea47e-7e6b-570a-8283-0272bcc2f521,0.0,140.0,140.0,2018,0.282609,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""green_matches_count"":2,""has_green_emails"":tr..."

In [4]:
#reorg dataframe with only columns deemed necessary (removing majority null columns as well as physical characteristics not related to ownership)
#removing "owner_std_name2_full" etc was only hesitation point, but any discrepancies in ownership type from there and std1 were negligible
df = df.iloc[:, [0,17,22,42,45,47,51,66,67,73,97]]

In [5]:
df.head()

,fips_state,fips,fips_county,mailing_std_house_nbr,mailing_std_mode,mailing_std_street,mailing_std_zip5,owner_std_name1_full,owner_std1_entity_type,parcel_shape_ids,std_land_use_code_category
0,AK,2122,Kenai Peninsula Borough,3745.0,LOOP,COMMUNITY PARK,99508.0,ALASKA MENTAL HEALTH AUTHORITY,business entity,"[""1145384340""]",Vacant Land
1,AK,2170,Matanuska-Susitna Borough,NaN,NaN,PO BOX 162,99645.0,ROCKEY ANDREW C,person,"[""935149401""]",Vacant Land
2,AL,1071,Jackson County,437.0,RD,RYAN,35752.0,MITCHELL JEFFREY KEITH,person,"[""875019999""]",Vacant Land
3,AL,1073,Jefferson County,1617.0,DR,MEADOWS,35235.0,JACKSON HENRETTE D,person,"[""1110679348""]",Vacant Land
4,AL,1133,Winston County,416.0,ST,LONG,35575.0,BARTON RILEY J,person,"[""1057188751""]",Vacant Land

In [6]:
#identifying missing data in columns
df.isnull().sum(axis = 0)

fips_state                     0
fips                           0
fips_county                    0
mailing_std_house_nbr         47
mailing_std_mode              67
mailing_std_street             5
mailing_std_zip5               5
owner_std_name1_full           0
owner_std1_entity_type         0
parcel_shape_ids               0
std_land_use_code_category     0
dtype: int64

In [7]:
#replacing null values with empty string
df.fillna('', inplace=True)

In [8]:
#combining columns into singular "address" column and dropping previous
all_columns = list(df)
df[all_columns] = df[all_columns].astype(str)

df['address'] = df[['mailing_std_house_nbr', 'mailing_std_street', 'mailing_std_mode','mailing_std_zip5']].agg(' '.join, axis=1)
df['address'] = df['address'].str.rstrip('.0')

df.drop(df.columns[[3, 4, 5, 6,]], axis = 1, inplace = True) 
df.head()

,fips_state,fips,fips_county,owner_std_name1_full,owner_std1_entity_type,parcel_shape_ids,std_land_use_code_category,address
0,AK,2122,Kenai Peninsula Borough,ALASKA MENTAL HEALTH AUTHORITY,business entity,"[""1145384340""]",Vacant Land,3745.0 COMMUNITY PARK LOOP 99508
1,AK,2170,Matanuska-Susitna Borough,ROCKEY ANDREW C,person,"[""935149401""]",Vacant Land,PO BOX 162 99645
2,AL,1071,Jackson County,MITCHELL JEFFREY KEITH,person,"[""875019999""]",Vacant Land,437.0 RYAN RD 35752
3,AL,1073,Jefferson County,JACKSON HENRETTE D,person,"[""1110679348""]",Vacant Land,1617.0 MEADOWS DR 35235
4,AL,1133,Winston County,BARTON RILEY J,person,"[""1057188751""]",Vacant Land,416.0 LONG ST 35575

In [9]:
#separating those owned by businesses vs individuals, into new dataframe for further analysis 
bizdf = (df[(df.owner_std1_entity_type.str.contains('business entity',case=False))].reset_index(drop=True)).sort_values(by=['fips_state'])

persondf = df[~df.owner_std1_entity_type.str.contains("business entity")]

In [10]:
#save to excel for inputting external research
#bizdf.to_csv('business_owned.csv')

### **Final Dataframe Combination**

In [11]:
biz2 = pd.read_csv('business_owned_fill.csv', index_col=0)
biz2.head()

,fips_state,fips,fips_county,owner_std_name1_full,owner_std1_entity_type,parcel_shape_ids,std_land_use_code_category,address,Owner Name
0,AK,2122,Kenai Peninsula Borough,ALASKA MENTAL HEALTH AUTHORITY,business entity,"[""1145384340""]",Vacant Land,3745.0 COMMUNITY PARK LOOP 99508,MIKE ABBOT
1,AR,5031,Craighead County,G & P DEVELOPMENT LLC,business entity,"[""1128034052""]",Commercial General/Misc.,4257.0 ANNADALE CIR 72404,MICHELLE YANG
2,CA,6041,Marin County,PLACE MOULIN,person,"[""1125026597""]",Vacant Land,1101.0 5TH AVE 94901,THOMAS MONAHAN
3,CA,6025,Imperial County,U S A BLM,business entity,"[""1048031225""]",Vacant Land,6221.0 BOX SPRINGS BLVD 92507,RIVERSIDE COUNTY ECONOMIC DEVELOPMENT AGENCY
4,CA,6037,Los Angeles County,STARKE PETRA,person,"[""1114950366""]",Vacant Land,1500.0 BENEDICT CANYON DR 90210,PETRA STARKE

In [12]:
#simplify df columns then rename
biz2 = biz2[['fips_state', 'owner_std1_entity_type','address','Owner Name']]
biz2.columns = ['fips_state','entity_type','address','owner name']
biz2.head()

,fips_state,entity_type,address,owner name
0,AK,business entity,3745.0 COMMUNITY PARK LOOP 99508,MIKE ABBOT
1,AR,business entity,4257.0 ANNADALE CIR 72404,MICHELLE YANG
2,CA,person,1101.0 5TH AVE 94901,THOMAS MONAHAN
3,CA,business entity,6221.0 BOX SPRINGS BLVD 92507,RIVERSIDE COUNTY ECONOMIC DEVELOPMENT AGENCY
4,CA,person,1500.0 BENEDICT CANYON DR 90210,PETRA STARKE

In [13]:
#load in df of person-owned properties and perform same
persondf = persondf[['fips_state','owner_std1_entity_type','address', 'owner_std_name1_full']]
persondf.columns = ['fips_state','entity_type','address','owner name']
persondf.head()

  fips_state entity_type                  address               owner name
1         AK      person        PO BOX 162  99645          ROCKEY ANDREW C
2         AL      person      437.0 RYAN RD 35752   MITCHELL JEFFREY KEITH
3         AL      person  1617.0 MEADOWS DR 35235       JACKSON HENRETTE D
4         AL      person      416.0 LONG ST 35575           BARTON RILEY J
5         AL      person   510.0 TREMONT ST 36701  STROTHER CLAUDE CHAMERS

In [14]:
owners_df = pd.concat([biz2, persondf], axis=0)
owners_df.head()

,fips_state,entity_type,address,owner name
0,AK,business entity,3745.0 COMMUNITY PARK LOOP 99508,MIKE ABBOT
1,AR,business entity,4257.0 ANNADALE CIR 72404,MICHELLE YANG
2,CA,person,1101.0 5TH AVE 94901,THOMAS MONAHAN
3,CA,business entity,6221.0 BOX SPRINGS BLVD 92507,RIVERSIDE COUNTY ECONOMIC DEVELOPMENT AGENCY
4,CA,person,1500.0 BENEDICT CANYON DR 90210,PETRA STARKE

In [17]:
owners_df.to_csv('reonomy_exercise_final.csv')